services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist
    ports:
      - "80:80"